export { H1 } from "./H1";
export { H2 } from "./H2";
export { H3 } from "./H3";
export { H4 } from "./H4";
export { TextPrimary } from "./TextPrimary";
export { TextSecondary } from "./TextSecondary";
export { InlinePrimary } from "./InlinePrimary";
export { InlineSecondary } from "./InlineSecondary";
export { Bold } from "./Bold";
